---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgCAJSWAUYD8XUe+mupLPES6l2RMe1uXtAlZvJ+1xUL9XSvSjjW8yioeYQZTSD140c+emzh6aW/9+aMJZhb1PNKMHfs0VVsTJVuF7cHuVEKBMMxu0iPXgAwbnLyu1sepufDAb0AjnaHpv37VHFQsyCV2HLUul3gr6mikiDsin9ofn/BGwpl5QynMVg8cVseifQNUTnPJleKTNXyXfALu1M1JIRcyiNSowc2Bfx50FU1+QMQqKEGYWf7kkuI0ldilhGcz5xy6resIMbMhA3bB08Q0ZQ1SNMEy/63QxzqGm5NSxXrgu3OTZBAym1TlsZdp3VC9yqoDeov1A+IJydQ1c2GCbpxRJiW7hxwiRyGR4dqZSf0xn2vZigNm9gqydxPvjPXozYOVH5OdSo7wC5c4DyV4Jyrhp/hgFbvahkd4KpKNmymWp4smMuhH6X4RdCFKXpjZmurJZ7FKLbZrnA5k5N/5AKAP7FKZH0ynIXlkuVE72Sib4iF0ZHOuPCXJaYnwd44LUPFWKRZvMc2K1beHbRenyCjULqmG6kp0PUHxJ/FeNOWbzecWSE9Ctn1EFyNbqjbgOmTK3N2kHXq4vnAHiIdogl572P4+wc8XO2HtU99JjJEEwJSzLG1pqo2g9E6WG3BoLWam+uRYl37DXW7bjUo4ojKe1SgkMvdtP5j0+q8ItsJeAVRsvjNmxfeTHQ5NexJDKqPePQLBN+8=
    username: AgADA5GqoZ0EAdRE1FciZyeMfphTlUwl9lUDtRe7KHw8WMZZ+QMoik8T5GLixrr157YeJBUCzyTUsu+U72UEW8KVZWuWuEWPYGxsMz7V9GoF0gwHPoVM2WpHjihpDqoV9d7/ixjgpI8CNWaurbyLCXa60fazxKjauNKPhtLsl/XGqSU6S83nO+uRuau4YPEtEIID5Fj+xd147a8gWDl6jCZNFGl2Fc7cYByimZf7YLd7FC5wyBdD4kGDG1/4VxTDUPpdZZVQ+qQe8glDQ9Lk45Voq0XbmsrfEIEIuBtJHCaDJ9tPB83aK0YuYnSrvdGEw1e3hYPyKXD4fyLjrkx5tTwSRBRjlfHKvUdLHY9c5l5VvCZgZxwnHYfvYaEEBg5YKCM1KI0nBHDGHJPg35yG4bNG+AH4eADfPWenQdUtu31egVTGDkIrbFVd/U3OzGYzEbgFSQqkfNAa/UAr0eh6kS5GHSgc1DfEuz9MFRtkma2S3NB5ILp9WMzCyTtM12lIEsCRDrry8ocpE2FQT01k/kqs+Zksp+C684hyTO8gQOPkNoRP6JdL8HLYDRWWXTQMz/5DI36A13/M9K2BIzAQJ7N5ef6+qO099rcOe+3O+qfBvGYS9eW6VPiVBjht7HG1rzK3EgXgaVtF10c5/1QElrsN4+tAisWon1QHV2E1x/sDpYdmgIlRQ4TfeIIZWzqUo1P3VhXfMw==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
