name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run tfsec on Terraform folder
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ./terraform

      # Step 3: Rename Dockerfile if needed
      - name: Rename Dockerfile if needed
        run: |
          if [ -f dockerfile.txt ]; then mv dockerfile.txt Dockerfile; fi

      # Step 4: Build Docker Image
      - name: Build Docker image
        run: docker build -t myapp:latest .

      # Step 5: Scan Docker image with Trivy
      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true

      # Step 6: Install kubectl
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 7: Install kubeseal
      - name: Install kubeseal
        run: |
          wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.25.0/kubeseal-0.25.0-linux-amd64.tar.gz
          tar -xvzf kubeseal-0.25.0-linux-amd64.tar.gz
          sudo mv kubeseal /usr/local/bin/kubeseal

      # Step 8: Apply SealedSecrets
      - name: Apply SealedSecrets
        run: |
          kubectl apply -f k8s-manifests/sealed-secrets/

      # Step 9: Deploy Application to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s-manifests/


